### ISSUE TITLE
Proposal: Measures

### ISSUE THREAD

**Issue by itsWihy** [Programming-TRIGON/RobotCode2024#42]
The units class in WPILib is very cool, ensuring you never get confused using units and allowing for very easy conversions.
In my humble opinion, integrating that into the code would be quite beneficial to both future you and other people coding, which won't have to _think_ while using units

**Comment by levyishai** [comment]
Nah

**Comment by itsWihy** [comment]
gae

**Comment by itsWihy** [comment]
I know u dont want to but I wanna know why

**Comment by levyishai** [comment]
This is just too memory inefficient.
Using mutable measures is too messy. 
We already have too many overruns.

**Comment by itsWihy** [comment]
who said mutable

**Comment by itsWihy** [comment]
instead of
double rotationsPerSecond
you have
Velocity<Angle> rotations

**Comment by levyishai** [comment]
To solve for inefficiency..

**Comment by itsWihy** [comment]
so using normal measures is too inefficient, therefore you ahve to use mutable measures, which is ugly?

**Comment by levyishai** [comment]
Yes.
Imo, normal measures are also a bit messy.

**Comment by itsWihy** [comment]
Ok.
I'm going to migrate all of my variables to Measures, _measure_ the memory usage, then try the same with using no measures at all
I'll update once I get a robot (ofir is gay)
